version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -O https://amazonaws.com
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - # Replace <ACCOUNT_ID> with your 12-digit AWS account number
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 259151462279.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=259151462279://
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo Connecting to EKS and Deploying...
      - aws eks update-kubeconfig --region us-east-1 --name brain
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml
      - echo Deployment complete. Fetching LoadBalancer URL...
      - kubectl get svc brain-tasks-service
