version: 0.2

phases:
  install:
    commands:
      - echo "No installation needed - files are pre-built."
  build:
    commands:
      - echo "Moving files to deployment..."
artifacts:
  files:
    - '**/*'
  base-directory: dist

